routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();



Route::get('front/{identifier}' , 'Visitors\VisitorFrontController@create')->name('visitors.front');
Route::get('employees/search' , 'Employees\EmployeeSearchController@show')->name('employees.search');
Route::resource('visitors', 'VisitorsController');
Route::group(['middleware' => ['auth','tenant']] , function(){
	Route::get('/home', 'HomeController@index')->name('home');
	Route::get('/reports', 'ReportsController@index')->name('reports');	
	Route::get('settings' , 'SettingsController@index')->name('settings.index');
	Route::post('welcome_message/update' , 'SettingsController@updateWelcomeMessage')->name('welcome.message.update');
	Route::post('avatar/upload' , 'AvatarController@store')->name('avatar.upload');
	Route::post('avatar/update' , 'AvatarController@updateAvatar')->name('avatar.update');
	Route::get('visitor/status/update' , 'Visitors\VisitorStatusController@update')->name('visitor.status.update');
	Route::get('my/visitors' , 'Visitors\MyVisitorsController@index')->name('my.visitors');
	Route::resource('admins', 'AdminsController');
	Route::resource('employees', 'EmployeesController');
	Route::resource('departments' , 'DepartmentsController');
	Route::get('lang/{lang}' , 'LanguageController@switchLang')->name('lang.switch');
	Route::get('visitors/by/date' , 'ReportsController@visitorsByDate')->name('visitors.by.date');
	Route::get('visitor/leave' , 'Visitors\VisitorLeaveController@create')->name('visitor.leave');
	Route::group(['prefix' => 'datatable'] , function(){

		Route::get('admins' , 'DataTablesController@admins')->name('datatable.admins');
		Route::get('employees' , 'DataTablesController@employees')->name('datatable.employees');
		Route::get('departments' , 'DataTablesController@departments')->name('datatable.departments');
		Route::get('visitors' , 'DataTablesController@visitors')->name('datatable.visitors');
		Route::get('my_visitors' , 'DataTablesController@myVisitors')->name('datatable.myVisitors');


	});
});

resources/views/partials/_btn-create.blade.php
<button id="adminSubmit" type="submit" class="btn btn-primary ladda-button waves-effect waves-light waves-round" data-style="slide-right" data-plugin="ladda" disabled>
	<span class="ladda-label">{{ __('Create') }}
		<i class="icon md-long-arrow-right ml-10" aria-hidden="true"></i>
	</span>
	<span class="ladda-spinner"></span>
	<div class="ladda-progress" style="width: 0px;"></div>
</button>

resources/views/partials/_btn-update.blade.php
<button type="submit" class="btn btn-primary ladda-button waves-effect waves-light waves-round" data-style="slide-right" data-plugin="ladda">
	<span class="ladda-label">{{ __('Update') }}<i class="icon md-long-arrow-right ml-10" aria-hidden="true"></i></span>
	<span class="ladda-spinner"></span>
	<div class="ladda-progress" style="width: 0px;"></div>
</button>

resources/views/partials/_menubar.blade.php
<div class="site-menubar">
	<div class="site-menubar-body">
		<div>
			<div>
				<ul class="site-menu" data-plugin="menu">
					<li class="site-menu-item">
						<a href="{{ url('/home') }}" dropdown-badge="false">
							<span class="site-menu-title">{{ __('Dashboard')}} </span>
							<img src="{{ asset('admin/images/home.png')}}" class="site-menu-item-img" alt="">
						</a>
					</li>
					<li class="site-menu-item">
						<a href="{{ url('/visitors') }}" dropdown-badge="false">
							<span class="site-menu-title">{{ __('Visitors')}} </span>
							<img src="{{ asset('admin/images/visitors.png')}}" class="site-menu-item-img" alt="">
						</a>
					</li>
					<li class="site-menu-item">
						<a href="{{ url('/employees') }}" dropdown-badge="false">
							<span class="site-menu-title">{{ __('Employees')}} </span>
							<img src="{{ asset('admin/images/employee.png')}}" class="site-menu-item-img" alt="">
						</a>
					</li>
					<li class="site-menu-item">
						<a href="{{ url('/admins') }}" dropdown-badge="false">
							<span class="site-menu-title">{{ __('Admins')}} </span>
							<img src="{{ asset('admin/images/admin.png')}}" class="site-menu-item-img" alt="">
						</a>
					</li>
					<li class="site-menu-item">
						<a href="{{ url('/departments') }}" dropdown-badge="false">
							<span class="site-menu-title">{{ __('Departments')}} </span>
							<img src="{{ asset('admin/images/sections.png')}}" class="site-menu-item-img" alt="">
						</a>
					</li>
					<li class="site-menu-item">
						<a href="{{ url('/settings') }}" dropdown-badge="false">
							<span class="site-menu-title">{{ __('Settings')}} </span>
							<img src="{{ asset('admin/images/settings.png')}}" class="site-menu-item-img" alt="">
						</a>
					</li>
					<li class="site-menu-item">
						<a href="{{ url('/reports') }}" dropdown-badge="false">
							<span class="site-menu-title">{{ __('Reports')}} </span>
							<img src="{{ asset('admin/images/reports.png')}}" class="site-menu-item-img" alt="">
						</a>
					</li>
					{{--  @if(auth()->user()->hasRole(['super_admin' , 'admin']))
					<li class="site-menu-item has-sub">
						<a href="javascript:void(0)" dropdown-badge="false">
							<i class="site-menu-icon md-assignment-account" aria-hidden="true"></i>
							<span class="site-menu-title">Admins</span>
							<span class="site-menu-arrow"></span>
						</a>
						<ul class="site-menu-sub">
							<li class="site-menu-item">
								<a class="animsition-link" href="{{ route('admins.create')}}">
									<span class="site-menu-title">Add Admin</span>
								</a>
							</li>
							<li class="site-menu-item">
								<a class="animsition-link" href="{{ route('admins.index')}}">
									<span class="site-menu-title">View Admins</span>
								</a>
							</li>
						</ul>
					</li>
					@endif
					@permission('create_employee')
					<li class="site-menu-category">Employees</li>
					<li class="site-menu-item has-sub">
						<a href="javascript:void(0)" dropdown-badge="false">
							<i class="site-menu-icon md-nature-people" aria-hidden="true"></i>
							<span class="site-menu-title">Employees</span>
							<span class="site-menu-arrow"></span>
						</a>
						<ul class="site-menu-sub">
							<li class="site-menu-item">
								<a class="animsition-link" href="{{ route('employees.create')}}">
									<span class="site-menu-title">Add Employees</span>
								</a>
							</li>
							<li class="site-menu-item">
								<a class="animsition-link" href="{{ route('employees.index')}}">
									<span class="site-menu-title">View Employees</span>
								</a>
							</li>
						</ul>
					</li>
					@endpermission
					<li class="site-menu-item has-sub">
						<a href="javascript:void(0)">
							<i class="site-menu-icon md-group-work" aria-hidden="true"></i>
							<span class="site-menu-title">Visitors</span>
							<span class="site-menu-arrow"></span>
						</a>
						<ul class="site-menu-sub">
							<li class="site-menu-item">
								<a class="animsition-link" href="{{ route('visitors.create')}}">
									<span class="site-menu-title">Invite Visitor</span>
								</a>
							</li>
							@if(auth()->user()->hasRole(['employee' , 'admin']))
								<li class="site-menu-item">
									<a class="animsition-link" href="{{ route('my.visitors')}}">
										<span class="site-menu-title">My Visitors</span>
									</a>
								</li>
							@endif
							@if(auth()->user()->hasRole(['super_admin' , 'admin']))
								<li class="site-menu-item">
									<a class="animsition-link" href="{{ route('visitors.index')}}">
										<span class="site-menu-title">View All Visitors</span>
									</a>
								</li>
							@endif
						</ul>
					</li>
					<li class="site-menu-item has-sub">
						<a href="javascript:void(0)" dropdown-badge="false">
							<i class="site-menu-icon md-view-comfy" aria-hidden="true"></i>
							<span class="site-menu-title">Departments</span>
							<span class="site-menu-arrow"></span>
						</a>
						<ul class="site-menu-sub">
							<li class="site-menu-item">
								<a class="animsition-link" href="{{ route('departments.create')}}">
									<span class="site-menu-title">Add Department</span>
								</a>
							</li>
							<li class="site-menu-item">
								<a class="animsition-link" href="{{ route('departments.index')}}">
									<span class="site-menu-title">View Departments</span>
								</a>
							</li>
						</ul>
					</li>  --}}
				</ul>
			</div>
		</div>
	</div>
</div>

resources/views/partials/_nav.blade.php
<nav class="site-navbar navbar navbar-default navbar-fixed-top navbar-mega navbar-inverse" role="navigation">
	<div class="navbar-header">
		<button type="button" class="navbar-toggler hamburger hamburger-close navbar-toggler-left hided" data-toggle="menubar">
			<span class="sr-only">Toggle navigation</span>
			<span class="hamburger-bar"></span>
		</button>
		<button type="button" class="navbar-toggler collapsed" data-target="#site-navbar-collapse" data-toggle="collapse">
			<i class="icon md-more" aria-hidden="true"></i>
		</button>
		<div class="navbar-brand navbar-brand-center site-gridmenu-toggle" data-toggle="gridmenu">
			{{--  <img class="navbar-brand-logo" src="../assets/images/logo.png" title="Remark">  --}}
			<span class="navbar-brand-text hidden-xs-down"> Venvoy</span>
		</div>
		<button type="button" class="navbar-toggler collapsed" data-target="#site-navbar-search" data-toggle="collapse">
			<span class="sr-only">Toggle Search</span>
			<i class="icon md-search" aria-hidden="true"></i>
		</button>
	</div>

	<div class="navbar-container container-fluid">
		<!-- Navbar Collapse -->
		<div class="collapse navbar-collapse navbar-collapse-toolbar" id="site-navbar-collapse">
			<!-- Navbar Toolbar -->
			<ul class="nav navbar-toolbar">
				<li class="nav-item hidden-float" id="toggleMenubar">
					<a class="nav-link" data-toggle="menubar" href="#" role="button">
						<i class="icon hamburger hamburger-arrow-left">
							<span class="sr-only">Toggle menubar</span>
							<span class="hamburger-bar"></span>
						</i>
					</a>
				</li>
			</ul>
			<!-- End Navbar Toolbar -->

			<!-- Navbar Toolbar Right -->
			<ul class="nav navbar-toolbar navbar-right navbar-toolbar-right">
				<li class="nav-item dropdown">
					<a class="nav-link" data-toggle="dropdown" href="javascript:void(0)" data-animation="scale-up" aria-expanded="false" role="button">
						<span class="flag-icon flag-icon-{{ config('languages')[app()->getLocale()]['icon'] }}"></span>
					</a>
					<div class="dropdown-menu" role="menu">
						@foreach(config('languages') as $lang => $language)
						
							@if($lang != app()->getLocale())
								<a class="dropdown-item" href="{{ route('lang.switch', $lang) }}" role="menuitem">
									<span class="flag-icon flag-icon-{{ $language['icon'] }}"></span> {{ $language['name'] }}
								</a>
							@endif
						@endforeach
					</div>
				</li>
				<li class="nav-item dropdown">
					<a class="nav-link navbar-avatar" data-toggle="dropdown" href="#" aria-expanded="false" data-animation="scale-up" role="button">
						<span class="avatar avatar-online">
							<img src="@if(!auth()->user()->avatar_id) {{ asset('images/avatars/placeholder.png')}} @else {{ auth()->user()->avatar->path()}} @endif" alt="...">
							<i></i>
						</span>
					</a>
					<div class="dropdown-menu" role="menu">
						<a class="dropdown-item" href="{{ route('settings.index') }}" role="menuitem">
							<i class="icon md-settings" aria-hidden="true"></i> {{ __('Settings') }}</a>
						<div class="dropdown-divider"></div>
						<a class="dropdown-item" onclick="event.preventDefault();document.getElementById('logout-form').submit();" role="menuitem"><i class="icon md-power" aria-hidden="true"></i> {{ __('Logout') }}</a>
						<form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                    		{{ csrf_field() }}
                		</form>
					</div>
				</li>
			</ul>
			<!-- End Navbar Toolbar Right -->
		</div>
		<!-- End Navbar Collapse -->

		<!-- Site Navbar Seach -->
		<div class="collapse navbar-search-overlap" id="site-navbar-search">
			<form role="search">
				<div class="form-group">
					<div class="input-search">
						<i class="input-search-icon md-search" aria-hidden="true"></i>
						<input type="text" class="form-control" name="site-search" placeholder="Search...">
						<button type="button" class="input-search-close icon md-close" data-target="#site-navbar-search" data-toggle="collapse" aria-label="Close"></button>
					</div>
				</div>
			</form>
		</div>
		<!-- End Site Navbar Seach -->
	</div>
</nav>