routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();



Route::get('front/{identifier}' , 'Visitors\VisitorFrontController@create')->name('visitors.front');
Route::get('employees/search' , 'Employees\EmployeeSearchController@show')->name('employees.search');
Route::resource('visitors', 'VisitorsController');
Route::group(['middleware' => ['auth','tenant']] , function(){
	Route::get('/home', 'HomeController@index')->name('home');
	Route::get('/reports', 'ReportsController@index')->name('reports');	
	Route::get('settings' , 'SettingsController@index')->name('settings.index');
	Route::post('welcome_message/update' , 'SettingsController@updateWelcomeMessage')->name('welcome.message.update');
	Route::post('avatar/upload' , 'AvatarController@store')->name('avatar.upload');
	Route::post('avatar/update' , 'AvatarController@updateAvatar')->name('avatar.update');
	Route::get('visitor/status/update' , 'Visitors\VisitorStatusController@update')->name('visitor.status.update');
	Route::get('my/visitors' , 'Visitors\MyVisitorsController@index')->name('my.visitors');
	Route::resource('admins', 'AdminsController');
	Route::resource('employees', 'EmployeesController');
	Route::resource('departments' , 'DepartmentsController');
	Route::get('lang/{lang}' , 'LanguageController@switchLang')->name('lang.switch');
	Route::get('visitors/by/date' , 'ReportsController@visitorsByDate')->name('visitors.by.date');
	Route::get('visitor/leave' , 'Visitors\VisitorLeaveController@create')->name('visitor.leave');
	Route::group(['prefix' => 'datatable'] , function(){

		Route::get('admins' , 'DataTablesController@admins')->name('datatable.admins');
		Route::get('employees' , 'DataTablesController@employees')->name('datatable.employees');
		Route::get('departments' , 'DataTablesController@departments')->name('datatable.departments');
		Route::get('visitors' , 'DataTablesController@visitors')->name('datatable.visitors');
		Route::get('my_visitors' , 'DataTablesController@myVisitors')->name('datatable.myVisitors');


	});
});

resources/views/admins/create.blade.php
@extends('layouts.app')

@section('page-level-styles')
	<link rel="stylesheet" href="{{ asset('css/intlTelInput.css')}}">
@endsection

@section('content')
	
	<div class="page">
		<div class="page-content container">
			<div class="row">
				<div class="col-md-6">
					<div class="panel panel-primary panel-line">
						<div class="panel-heading">
							<h3 class="panel-title">
								Add New Admin
							</h3>
						</div>
						<div class="panel-body">
							<form autocomplete="off" method="POST" action="{{ route('admins.store') }}">
								{{ csrf_field() }}
								{{ method_field('POST') }}
	                            <div class="form-group{{ $errors->has('name') ? ' has-danger' : '' }}">
	                                <label for="name" class="col-md-4 control-label">{{ __('Name') }}</label>
	                                <div class="col-md-12">
	                                    <input id="name" type="text" class="form-control{{ $errors->has('name') ? ' is-invalid' : '' }}" value="{{ old('name') }}" name="name"  required autofocus>

	                                    @if ($errors->has('name'))
	                                        <span class="invalid-feedback">
	                                            <strong>{{ $errors->first('name') }}</strong>
	                                        </span>
	                                    @endif
	                                </div>
                            	</div>
	                            <div class="form-group{{ $errors->has('email') ? ' has-danger' : '' }}">
	                                <label for="email" class="col-md-4 control-label"> {{ __('Email') }}</label>

	                                <div class="col-md-12">
	                                    <input id="email" type="email" class="form-control{{ $errors->has('email') ? ' is-invalid' : '' }}" value="{{ old('email') }}" name="email"  required>

	                                    @if ($errors->has('email'))
	                                        <div class="invalid-feedback">
	                                            <strong>{{ $errors->first('email') }}</strong>
	                                        </div>
	                                    @endif
	                                </div>
	                            </div>
	                            <div class="form-group{{ $errors->has('phone') ? ' has-danger' : '' }}">
	                                <label for="email" class="col-md-4 control-label">{{ __('Phone') }}</label>

	                                <div class="col-md-12">
	                                    <input id="phone" type="text" class="form-control{{ $errors->has('phone') ? ' is-invalid' : '' }}" value="{{ old('phone') }}"  required>
										<input type="hidden" name="phone" value="" id="hiddenPhone">
										<span id="valid-msg" class="hide">✓ {{ __('Valid') }}</span>
										<span id="error-msg" class="hide">{{ __('Invalid') }}</span>
	                                    @if ($errors->has('phone'))
	                                        <div class="invalid-feedback" id="phone-invalid-feedback">
	                                            <strong>{{ $errors->first('phone') }}</strong>
	                                        </div>
	                                    @endif
	                                </div>
	                            </div>

								<button id="adminSubmit" type="submit" class="btn btn-primary ladda-button waves-effect waves-light waves-round" data-style="slide-right" data-plugin="ladda" disabled>
                        			<span class="ladda-label">{{ __('Create') }}<i class="icon md-long-arrow-right ml-10" aria-hidden="true"></i></span>
                      				<span class="ladda-spinner"></span><div class="ladda-progress" style="width: 0px;"></div>
                      			</button>
							</form>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>

@endsection

@section('page-level-scripts')
	<script src="{{asset('js/intlTelInput.min.js')}}"></script>
	<script>
		$(document).ready(function(){
			  var telInput = $("#phone"),
			  errorMsg = $("#error-msg"),
			  validMsg = $("#valid-msg");

			// initialise plugin
			telInput.intlTelInput({
			  utilsScript: "{{ asset('js/utils.js')}}"
			});

			var reset = function() {
			  telInput.removeClass("error");
			  errorMsg.addClass("hide");
			  validMsg.addClass("hide");
			};

			// on blur: validate
			telInput.blur(function() {
			  reset();
			  if ($.trim(telInput.val())) {
			    if (telInput.intlTelInput("isValidNumber")) {
			      validMsg.removeClass("hide");
				  $('#hiddenPhone').val($("#phone").intlTelInput("getNumber"));
			      $('#adminSubmit').removeAttr('disabled');
			    } else {
			      telInput.addClass("error");
			      errorMsg.removeClass("hide");
			    }
			  }
			});

			// on keyup / change flag: reset
			telInput.on("keyup change", reset);
		});
	</script>
@endsection

resources/views/admins/edit.blade.php
@extends('layouts.app')
@section('page-level-styles')
	<link rel="stylesheet" href="{{ asset('css/intlTelInput.css')}}">
@endsection
@section('content')
	
	<div class="page">
		<div class="page-content container">
			<div class="row">
				<div class="col-md-6">
					<div class="panel panel-primary panel-line">
						<div class="panel-heading">
							<h3 class="panel-title">
								Update Admin Information
							</h3>
						</div>
						<div class="panel-body">
							<form autocomplete="off" method="POST" action="{{ route('admins.update' , ['id' => $user->id]) }}">
								{{ csrf_field() }}
								{{ method_field('PATCH')}}
								<div class="form-group{{ $errors->has('name') ? ' has-danger' : '' }}">
	                                <label for="name" class="col-md-4 control-label">{{ __('Name') }}</label>
	                                <div class="col-md-12">
	                                    <input id="name" type="text" class="form-control{{ $errors->has('name') ? ' is-invalid' : '' }}" value="{{ $user->name }}" name="name"  required autofocus>

	                                    @if ($errors->has('name'))
	                                        <span class="invalid-feedback">
	                                            <strong>{{ $errors->first('name') }}</strong>
	                                        </span>
	                                    @endif
	                                </div>
                            	</div>
								<div class="form-group{{ $errors->has('email') ? ' has-danger' : '' }}">
	                                <label for="email" class="col-md-4 control-label">{{ __('Email') }}</label>

	                                <div class="col-md-12">
	                                    <input id="email" type="email" class="form-control{{ $errors->has('email') ? ' is-invalid' : '' }}" value="{{ $user->email }}" name="email"  required>

	                                    @if ($errors->has('email'))
	                                        <div class="invalid-feedback">
	                                            <strong>{{ $errors->first('email') }}</strong>
	                                        </div>
	                                    @endif
	                                </div>
	                            </div>
								<div class="form-group{{ $errors->has('phone') ? ' has-danger' : '' }}">
	                                <label for="email" class="col-md-4 control-label">{{ __('Phone') }}</label>

	                                <div class="col-md-12">
	                                    <input id="phone" type="text" class="form-control{{ $errors->has('phone') ? ' is-invalid' : '' }}" value="{{ $user->phone }}"  required>
										<input type="hidden" name="phone" value="{{ $user->phone }}" id="hiddenPhone">
										<span id="valid-msg" class="hide">✓ {{ __('Valid') }}</span>
										<span id="error-msg" class="hide">{{ __('Invalid') }}</span>
	                                    @if ($errors->has('phone'))
	                                        <div class="invalid-feedback" id="phone-invalid-feedback">
	                                            <strong>{{ $errors->first('phone') }}</strong>
	                                        </div>
	                                    @endif
	                                </div>
	                            </div>
								<button type="submit" class="btn btn-primary ladda-button waves-effect waves-light waves-round" data-style="slide-right" data-plugin="ladda">
                        			<span class="ladda-label">{{ __('Update') }}<i class="icon md-long-arrow-right ml-10" aria-hidden="true"></i></span>
                      				<span class="ladda-spinner"></span><div class="ladda-progress" style="width: 0px;"></div>
                      			</button>
							</form>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>

@endsection

@section('page-level-scripts')
	<script src="{{asset('js/intlTelInput.min.js')}}"></script>
	<script>
		$(document).ready(function(){
			  var telInput = $("#phone"),
			  errorMsg = $("#error-msg"),
			  validMsg = $("#valid-msg");

			// initialise plugin
			telInput.intlTelInput({
			  utilsScript: "{{ asset('js/utils.js')}}"
			});

			var reset = function() {
			  telInput.removeClass("error");
			  errorMsg.addClass("hide");
			  validMsg.addClass("hide");
			};

			// on blur: validate
			telInput.blur(function() {
			  reset();
			  if ($.trim(telInput.val())) {
			    if (telInput.intlTelInput("isValidNumber")) {
			      validMsg.removeClass("hide");
				  $('#hiddenPhone').val($("#phone").intlTelInput("getNumber"));
			      $('#adminSubmit').removeAttr('disabled');
			    } else {
			      telInput.addClass("error");
			      errorMsg.removeClass("hide");
			    }
			  }
			});

			// on keyup / change flag: reset
			telInput.on("keyup change", reset);
		});
	</script>
@endsection

resources/views/admins/index.blade.php
@extends('layouts.app')

@section('page-level-styles')
	<link rel="stylesheet" href="{{ asset('admin/vendor/datatables.net-bs4/dataTables.bootstrap4.min.css') }}">
@endsection

@section('content')
	<div class="page">
		<div class="page-content container">
			<div class="panel">
          <header class="panel-heading">
            <h3 class="panel-title">{{ __('Admins') }} <a href="{{ route('admins.create') }}" class="btn btn-primary create-btn">{{ __('Add Admin') }}</a></h3>
          </header>
          <div class="panel-body">
            <table class="table table-hover dataTable table-striped w-full" id="adminsTable">
              <thead>
                <tr>
                  <th>{{ __('Name') }}</th>
                  <th>{{ __('Email') }}</th>
                  <th>{{ __('Date') }}</th>
                  <th>{{ __('Actions') }}</th>
                </tr>
              </thead>
              <tbody>
              </tbody>
            </table>
          </div>
        </div>
        <!-- End Panel Table Tools -->
		</div>
	</div>
@endsection

@section('page-level-scripts')

    

	<script src="{{ asset('admin/vendor/datatables.net/jquery.dataTables.js') }}"></script>
    <script src="{{ asset('admin/vendor/datatables.net-bs4/dataTables.bootstrap4.js') }}"></script>
    <script src="{{ asset('admin/vendor/datatables.net-buttons/dataTables.buttons.min.js') }}"></script>
    <script src="{{ asset('admin/vendor/datatables.net-buttons/buttons.html5.min.js') }}"></script>
    <script src="{{ asset('admin/vendor/datatables.net-buttons/buttons.print.min.js') }}"></script>
    <script src="{{ asset('admin/vendor/datatables.net-buttons-bs4/buttons.bootstrap4.min.js')}}"></script>
    <script>
    	$(document).ready(function(){
    		$('#adminsTable').DataTable({
          language : {
						paginate : {
							previous : "{!! __('Previous') !!}",
							next : "{!! __('Next') !!}"
						},
						search : "{!! __('Search') !!}",
					},
    			processing : true,
    			serverSide : true,
    			ajax : '{!! route('datatable.admins') !!}',
    			columns: [
		            { data: 'name', name: 'name' },
		            { data: 'email', name: 'email' },
		            { data: 'created_at', name: 'created_at' },
		            { data : 'action' , name : 'action' , orderable: false, searchable: false}
		        ],
		        {{--  sDom: '<"dt-panelmenu clearfix"Bfr>t<"dt-panelfooter clearfix"ip>',
		        buttons: ['csv', 'print']  --}}
    		});
    	});
    </script>
@endsection