routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();



Route::get('front/{identifier}' , 'Visitors\VisitorFrontController@create')->name('visitors.front');
Route::get('employees/search' , 'Employees\EmployeeSearchController@show')->name('employees.search');
Route::resource('visitors', 'VisitorsController');
Route::group(['middleware' => ['auth','tenant']] , function(){
	Route::get('/home', 'HomeController@index')->name('home');
	Route::get('/reports', 'ReportsController@index')->name('reports');	
	Route::get('settings' , 'SettingsController@index')->name('settings.index');
	Route::post('welcome_message/update' , 'SettingsController@updateWelcomeMessage')->name('welcome.message.update');
	Route::post('avatar/upload' , 'AvatarController@store')->name('avatar.upload');
	Route::post('avatar/update' , 'AvatarController@updateAvatar')->name('avatar.update');
	Route::get('visitor/status/update' , 'Visitors\VisitorStatusController@update')->name('visitor.status.update');
	Route::get('my/visitors' , 'Visitors\MyVisitorsController@index')->name('my.visitors');
	Route::resource('admins', 'AdminsController');
	Route::resource('employees', 'EmployeesController');
	Route::resource('departments' , 'DepartmentsController');
	Route::get('lang/{lang}' , 'LanguageController@switchLang')->name('lang.switch');
	Route::get('visitors/by/date' , 'ReportsController@visitorsByDate')->name('visitors.by.date');
	Route::get('visitor/leave' , 'Visitors\VisitorLeaveController@create')->name('visitor.leave');
	Route::group(['prefix' => 'datatable'] , function(){

		Route::get('admins' , 'DataTablesController@admins')->name('datatable.admins');
		Route::get('employees' , 'DataTablesController@employees')->name('datatable.employees');
		Route::get('departments' , 'DataTablesController@departments')->name('datatable.departments');
		Route::get('visitors' , 'DataTablesController@visitors')->name('datatable.visitors');
		Route::get('my_visitors' , 'DataTablesController@myVisitors')->name('datatable.myVisitors');


	});
});

app/Http/Controllers/Employees/EmployeeSearchController.php
<?php

namespace App\Http\Controllers\Employees;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Queries\EmployeeSearch;

class EmployeeSearchController extends Controller
{
    public function show(Request $request)
    {
        $employees = new EmployeeSearch($request->q , $request->tenant , $request->department);
        return response()->json($employees());
    }
}

app/Http/Controllers/EmployeesController.php
<?php

namespace App\Http\Controllers;

use App\User;
use Illuminate\Http\Request;
use App\Events\EmployeeAdded;
use Twilio\Exceptions\RestException;
use App\Http\Requests\CreateEmployeeRequest;
use App\Repositories\Contracts\DepartmentRepository;
use App\Department;

class EmployeesController extends Controller
{
    protected $department;

    public function __construct(DepartmentRepository $department)
    {
        $this->department = $department;
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('employees.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $departments = Department::all();
        return view('employees.create' , compact('departments'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CreateEmployeeRequest $request)
    {
        $randomPassword = str_random(6);

        $user = User::create([
            'name' => $request->name,
            'email' => $request->email,
            'phone' => $request->phone,
            'password' => bcrypt($randomPassword),
            'department_id' => $request->department
        ]);

        $user->roles()->attach(3); 
        try {
            event(new EmployeeAdded($user , $randomPassword));
        } catch (RestException $e) {
            return redirect()->back()->with([
                    'message' => $e->getMessage(),
                    'alert-type' => 'error'
                ]);
        }
        

        return redirect()->route('employees.index')
                         ->with([
                                'message' => 'Successfully created Employee.',
                                'alert-type' => 'success'
                            ]);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $user = User::find($id);
        $departments = $this->department->all();
        return view('employees.edit' , ['user' => $user , 'departments' => $departments]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $employee = User::find($id);
        $request->validate([
            'name' => 'required|string|max:255',
            'email' => 'required|string|email|max:255|unique:users,email,' . $employee->id,
            'phone' => 'required|string|unique:users,phone,' . $employee->id,

        ]);
        
        $employee->name = $request->name;
        $employee->email = $request->email;
        $employee->phone = $request->phone;
        $employee->save();
        return redirect()->route('employees.index')->with(['message' => 'Successfully Updated!' , 'alert-type' => 'success']);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $user = User::find($id);
        $user->delete();
        return redirect()->route('employees.index')->with(['message' => 'Successfully Deleted!' , 'alert-type' => 'success']);
    }
}

resources/views/employees/create.blade.php
@extends('layouts.app')

@section('page-level-styles')
	<link rel="stylesheet" href="{{ asset('css/intlTelInput.css')}}">
@endsection

@section('content')
	
	<div class="page">
		<div class="page-content container">
			<div class="row">
				<div class="col-md-6">
					<div class="panel panel-primary panel-line">
						<div class="panel-heading">
							<h3 class="panel-title">
								{{ __('Add Employee') }}
							</h3>
						</div>
						<div class="panel-body">
							<form autocomplete="off" method="POST" action="{{ route('employees.store') }}">
								{{ csrf_field() }}
	                            <div class="form-group{{ $errors->has('name') ? ' has-danger' : '' }}">
	                                <label for="name" class="col-md-4 control-label">{{ __('Name') }}</label>
	                                <div class="col-md-12">
	                                    <input id="name" type="text" class="form-control{{ $errors->has('name') ? ' is-invalid' : '' }}" value="{{ old('name') }}" name="name"  required autofocus>

	                                    @if ($errors->has('name'))
	                                        <span class="invalid-feedback">
	                                            <strong>{{ $errors->first('name') }}</strong>
	                                        </span>
	                                    @endif
	                                </div>
                            	</div>
	                            <div class="form-group{{ $errors->has('email') ? ' has-danger' : '' }}">
	                                <label for="email" class="col-md-4 control-label">{{ __('Email') }}</label>

	                                <div class="col-md-12">
	                                    <input id="email" type="email" class="form-control{{ $errors->has('email') ? ' is-invalid' : '' }}" value="{{ old('email') }}" name="email"  required>

	                                    @if ($errors->has('email'))
	                                        <div class="invalid-feedback">
	                                            <strong>{{ $errors->first('email') }}</strong>
	                                        </div>
	                                    @endif
	                                </div>
	                            </div>
								<div class="form-group{{ $errors->has('phone') ? ' has-danger' : '' }}">
	                                <label for="email" class="col-md-4 control-label">{{ __('Phone')}}</label>

	                                <div class="col-md-12">
	                                    <input id="phone" type="text" class="form-control{{ $errors->has('phone') ? ' is-invalid' : '' }}" value="{{ old('phone') }}" required>
										<input type="hidden" name="phone" value="" id="hiddenPhone">
										<span id="valid-msg" class="hide">✓ {{ __('Valid') }}</span>
										<span id="error-msg" class="hide">{{ __('Invalid') }}</span>
	                                    @if ($errors->has('phone'))
	                                        <div class="invalid-feedback" id="phone-invalid-feedback">
	                                            <strong>{{ $errors->first('phone') }}</strong>
	                                        </div>
	                                    @endif
	                                </div>
	                            </div>
								<div class="form-group{{ $errors->has('department') ? ' has-danger' : '' }}">
	                                <label for="email" class="col-md-4 control-label">{{ __('Department') }}</label>

	                                <div class="col-md-12">
	                                    <select name="department" class="form-control">
											<option value="">{{ __('Select a Department')}}</option>
											@foreach($departments as $department)
												<option value="{{$department->id}}">{{ $department->name }}</option>
											@endforeach
										</select>

	                                    @if ($errors->has('department'))
	                                        <div class="invalid-feedback">
	                                            <strong>{{ $errors->first('department') }}</strong>
	                                        </div>
	                                    @endif
	                                </div>
	                            </div>
								@include('partials._btn-create')
							</form>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>

@endsection

@section('page-level-scripts')
	<script src="{{asset('js/intlTelInput.min.js')}}"></script>
	<script>
		$(document).ready(function(){
			  var telInput = $("#phone"),
			  errorMsg = $("#error-msg"),
			  validMsg = $("#valid-msg");

			// initialise plugin
			telInput.intlTelInput({
			  utilsScript: "{{ asset('js/utils.js')}}"
			});

			var reset = function() {
			  telInput.removeClass("error");
			  errorMsg.addClass("hide");
			  validMsg.addClass("hide");
			};

			// on blur: validate
			telInput.blur(function() {
			  reset();
			  if ($.trim(telInput.val())) {
			    if (telInput.intlTelInput("isValidNumber")) {
			      validMsg.removeClass("hide");
				  $('#hiddenPhone').val($("#phone").intlTelInput("getNumber"));
			      $('#adminSubmit').removeAttr('disabled');
			    } else {
			      telInput.addClass("error");
			      errorMsg.removeClass("hide");
			    }
			  }
			});

			// on keyup / change flag: reset
			telInput.on("keyup change", reset);
		});
	</script>
@endsection

resources/views/employees/edit.blade.php
@extends('layouts.app')
@section('page-level-styles')
	<link rel="stylesheet" href="{{ asset('css/intlTelInput.css')}}">
@endsection
@section('content')
	
	<div class="page">
		<div class="page-content container">
			<div class="row">
				<div class="col-md-6">
					<div class="panel panel-primary panel-line">
						<div class="panel-heading">
							<h3 class="panel-title">
								Update Employee Information
							</h3>
						</div>
						<div class="panel-body">
							<form  autocomplete="off" method="POST"  action="{{ route('employees.update' , ['id' => $user->id]) }}">
								{{ csrf_field() }}
								{{ method_field('PATCH')}}
	                            <div class="form-group{{ $errors->has('name') ? ' has-danger' : '' }}">
	                                <label for="name" class="col-md-4 control-label">{{ __('Name') }}</label>
	                                <div class="col-md-12">
	                                    <input id="name" type="text" class="form-control{{ $errors->has('name') ? ' is-invalid' : '' }}" name="name" value="{{ $user->name }}"  required autofocus>
	                                    @if ($errors->has('name'))
	                                        <span class="invalid-feedback">
	                                            <strong>{{ $errors->first('name') }}</strong>
	                                        </span>
	                                    @endif
	                                </div>
                            	</div>
	                            <div class="form-group{{ $errors->has('email') ? ' has-danger' : '' }}">
	                                <label for="email" class="col-md-4 control-label">{{ __('Email') }}</label>
	                                <div class="col-md-12">
	                                    <input id="email" type="email" class="form-control{{ $errors->has('email') ? ' is-invalid' : '' }}" name="email" value="{{ $user->email }}"  required>

	                                    @if ($errors->has('email'))
	                                        <div class="invalid-feedback">
	                                            <strong>{{ $errors->first('email') }}</strong>
	                                        </div>
	                                    @endif
	                                </div>
	                            </div>
	                            <div class="form-group{{ $errors->has('phone') ? ' has-danger' : '' }}">
	                                <label for="email" class="col-md-4 control-label">{{ __('Phone') }}</label>
	                                <div class="col-md-12">
	                                    <input id="phone" type="text" class="form-control{{ $errors->has('phone') ? ' is-invalid' : '' }}" value="{{ $user->phone }}" name="phone" required>
										<span id="valid-msg" class="hide">✓ {{__('Valid') }}</span>
										<span id="error-msg" class="hide">{{ __('Invalid') }}</span>
	                                    @if ($errors->has('phone'))
	                                        <div class="invalid-feedback" id="phone-invalid-feedback">
	                                            <strong>{{ $errors->first('phone') }}</strong>
	                                        </div>
	                                    @endif
	                                </div>
	                            </div>
								<div class="form-group{{ $errors->has('department') ? ' has-danger' : '' }}">
	                                <label for="email" class="col-md-4 control-label">{{ __('Department') }}</label>

	                                <div class="col-md-12">
	                                    <select name="department" class="form-control">
											<option value="">{{ __('Select a Department')}}</option>
											@foreach($departments as $department)
												<option value="{{$department->id}}"@if($user->department_id == $department->id) {{'selected'}} @endif>{{ $department->name }}</option>
											@endforeach
										</select>

	                                    @if ($errors->has('department'))
	                                        <div class="invalid-feedback">
	                                            <strong>{{ $errors->first('department') }}</strong>
	                                        </div>
	                                    @endif
	                                </div>
	                            </div>
								@include('partials._btn-update')
							</form>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>

@endsection

@section('page-level-scripts')
	<script src="{{asset('js/intlTelInput.min.js')}}"></script>
	<script>
		$(document).ready(function(){
			  var telInput = $("#phone"),
			  errorMsg = $("#error-msg"),
			  validMsg = $("#valid-msg");

			// initialise plugin
			telInput.intlTelInput({
			  utilsScript: "{{ asset('js/utils.js')}}"
			});

			var reset = function() {
			  telInput.removeClass("error");
			  errorMsg.addClass("hide");
			  validMsg.addClass("hide");
			};

			// on blur: validate
			telInput.blur(function() {
			  reset();
			  if ($.trim(telInput.val())) {
			    if (telInput.intlTelInput("isValidNumber")) {
			      validMsg.removeClass("hide");
				  $('#hiddenPhone').val($("#phone").intlTelInput("getNumber"));
			      $('#adminSubmit').removeAttr('disabled');
			    } else {
			      telInput.addClass("error");
			      errorMsg.removeClass("hide");
			    }
			  }
			});

			// on keyup / change flag: reset
			telInput.on("keyup change", reset);
		});
	</script>
@endsection

resources/views/employees/index.blade.php
@extends('layouts.app')

@section('page-level-styles')
	<link rel="stylesheet" href="{{ asset('admin/vendor/datatables.net-bs4/dataTables.bootstrap4.min.css') }}">
@endsection

@section('content')
	<div class="page">
		<div class="page-content container">
			<div class="panel">
          <div class="panel-heading">
            <h3 class="panel-title">{{ __('Employees') }} <a href="{{ route('employees.create') }}" class="btn btn-primary create-btn">{{ __('Add Employee') }}</a></h3>
          </div>
          <div class="panel-body">
            <table class="table table-hover dataTable table-striped w-full" id="employeesTable">
              <thead>
                <tr>
                  <th>{{ __('Name') }}</th>
                  <th>{{ __('Email') }}</th>
							<th>{{ __('Date') }}</th>
							<th>{{ __('Actions') }}</th>
                </tr>
              </thead>
              <tbody>
              </tbody>
            </table>
          </div>
        </div>
        <!-- End Panel Table Tools -->
		</div>
	</div>
@endsection

@section('page-level-scripts')

    

	<script src="{{ asset('admin/vendor/datatables.net/jquery.dataTables.js') }}"></script>
    <script src="{{ asset('admin/vendor/datatables.net-bs4/dataTables.bootstrap4.js') }}"></script>
    <script src="{{ asset('admin/vendor/datatables.net-buttons/dataTables.buttons.min.js') }}"></script>
    <script src="{{ asset('admin/vendor/datatables.net-buttons/buttons.html5.min.js') }}"></script>
    <script src="{{ asset('admin/vendor/datatables.net-buttons/buttons.print.min.js') }}"></script>
    <script src="{{ asset('admin/vendor/datatables.net-buttons-bs4/buttons.bootstrap4.min.js')}}"></script>
    <script>
    	$(document).ready(function(){
    		$('#employeesTable').DataTable({
          language : {
						paginate : {
							previous : "{!! __('Previous') !!}",
							next : "{!! __('Next') !!}"
						},
						search : "{!! __('Search') !!}",
					},
    			processing : true,
    			serverSide : true,
    			ajax : '{!! route('datatable.employees') !!}',
    			columns: [
		            { data: 'name', name: 'name' },
		            { data: 'email', name: 'email' },
		            { data: 'created_at', name: 'created_at' },
		            { data : 'action' , name : 'action' , orderable: false, searchable: false}
		        ],
		        {{--  sDom: '<"dt-panelmenu clearfix"Bfr>t<"dt-panelfooter clearfix"ip>',
		        buttons: ['csv', 'print']  --}}
    		});
    	});
    </script>
@endsection